/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControlAccount;
import information.InfoAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author binhminh
 */
public class ViewSignUp extends javax.swing.JFrame {

    /**
     * Creates new form Manager_Login
     */
    DefaultTableModel model;

    public ViewSignUp() {
        initComponents();
        btDelete.setEnabled(false);
        btUpdate.setEnabled(false);
    }
    
    public ViewSignUp(int i){
        initComponents();
        model = (DefaultTableModel) tbAccount.getModel();
        hienThiTBAccount();
    }
    
    public void hienThiTBAccount() {
        ArrayList<InfoAccount> list = new ArrayList();
        ControlAccount account = new ControlAccount();
        list = account.getAccounts();
        for (InfoAccount a : list) {
            model.addRow(new Object[]{
                a.getId(), a.getUserName(), 
                a.getPassWord(), a.getRole() , 
                a.getSdt(), a.getHovaten(), a.getKhoa()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        textsdt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textHoVaTen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbKhoa = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btAddNew = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAccount = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setLocation(new java.awt.Point(550, 250));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Xinchao: ");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("ban");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(7, 2));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID");
        jPanel3.add(jLabel3);

        txtid.setEnabled(false);
        jPanel3.add(txtid);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Username");
        jPanel3.add(jLabel4);
        jPanel3.add(txtusername);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password");
        jPanel3.add(jLabel5);
        jPanel3.add(txtpassword);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Role");
        jPanel3.add(jLabel6);

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "teacher", "guest" }));
        jPanel3.add(cbRole);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SĐT ");
        jPanel3.add(jLabel7);
        jPanel3.add(textsdt);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Họ và tên");
        jPanel3.add(jLabel8);
        jPanel3.add(textHoVaTen);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Khoa");
        jPanel3.add(jLabel9);

        cbKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT", "Toán&Tin" }));
        jPanel3.add(cbKhoa);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        btAddNew.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btAddNew.setForeground(java.awt.Color.red);
        btAddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/themnhanvien.png"))); // NOI18N
        btAddNew.setText("Add New");
        btAddNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btAddNewMouseClicked(evt);
            }
        });
        jPanel4.add(btAddNew);

        btUpdate.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btUpdate.setForeground(java.awt.Color.red);
        btUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/suanguoidoc.png"))); // NOI18N
        btUpdate.setText("Update");
        btUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btUpdateMouseClicked(evt);
            }
        });
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(btUpdate);

        btDelete.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btDelete.setForeground(java.awt.Color.red);
        btDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/xoanhanvien.png"))); // NOI18N
        btDelete.setText("Delete");
        btDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDeleteMouseClicked(evt);
            }
        });
        jPanel4.add(btDelete);

        btExit.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btExit.setForeground(java.awt.Color.red);
        btExit.setText("Exit");
        btExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExitMouseClicked(evt);
            }
        });
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        jPanel4.add(btExit);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Password", "Role", "SĐT", "Họ và tên", "Khoa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAccountMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbAccount);

        jMenu1.setText("File");

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Floppy-Small-icon.png"))); // NOI18N
        jMenu3.setText("Save");
        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator1);

        menuexit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        menuexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon.png"))); // NOI18N
        menuexit.setText("Exit ");
        jMenu1.add(menuexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btExitActionPerformed

    private void btExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        if( btDelete.isEnabled() == true){
            System.exit(0);
        }
    }//GEN-LAST:event_btExitMouseClicked

    private void btAddNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAddNewMouseClicked
        if ( txtpassword.getText().equals("") | txtusername.getText().equals("")) {
            JOptionPane.showConfirmDialog(rootPane, "Bạn chưa nhập đủ thông tin");
        } else {
            int kt = 0;
            ControlAccount account = new ControlAccount();
            kt = account.themAccount( txtusername.getText(), 
                                    txtpassword.getText(), 
                                    cbRole.getSelectedItem().toString(),
                                    textsdt.getText().trim(),
                                    textHoVaTen.getText().trim(), 
                                    cbKhoa.getSelectedItem().toString());
            if (kt != 0) {
                model.addRow(new Object[]{
                    0 ,txtusername.getText(), txtpassword.getText(), cbRole.getSelectedItem().toString(),
                    textsdt.getText().trim(),textHoVaTen.getText().trim(), cbKhoa.getSelectedItem().toString()
                });
                JOptionPane.showMessageDialog(null, "Đăng kí thành công !", "Chúc mừng!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Đăng kí chưa thành công !", "Đáng tiếc", JOptionPane.ERROR_MESSAGE);
            }

        }


    }//GEN-LAST:event_btAddNewMouseClicked

    private void btDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDeleteMouseClicked
        ControlAccount account = new ControlAccount();
        int row = tbAccount.getSelectedRow();
        if(row > -1){
            account.xoaAccount((int) tbAccount.getValueAt(row, 0));
            model.removeRow(row);
        }else{
            JOptionPane.showMessageDialog(null, "Hãy chọn 1 hàng", "NOTE", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_btDeleteMouseClicked

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        
        ControlAccount account = new ControlAccount();
        int row = tbAccount.getSelectedRow();
        if(row > -1){
            int kt=0;
            account.xoaAccount((int) tbAccount.getValueAt(row, 0));
            kt = account.themAccount( txtusername.getText(), 
                                    txtpassword.getText(), 
                                    cbRole.getSelectedItem().toString(),
                                    textsdt.getText().trim(),
                                    textHoVaTen.getText().trim(), 
                                    cbKhoa.getSelectedItem().toString());
            model.removeRow(row);
            model.addRow(new Object[]{
                    kt ,txtusername.getText(), txtpassword.getText(), cbRole.getSelectedItem().toString(),
                    textsdt.getText().trim(),textHoVaTen.getText().trim(), cbKhoa.getSelectedItem().toString()
            });
        }else{
            JOptionPane.showMessageDialog(null, "Hãy chọn 1 hàng", "NOTE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUpdateMouseClicked
        
    }//GEN-LAST:event_btUpdateMouseClicked

    private void tbAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAccountMouseClicked
        int row = tbAccount.getSelectedRow();
        if(evt.getClickCount() ==2){
            txtusername.setText(tbAccount.getValueAt(row , 1).toString());
            txtpassword.setText(tbAccount.getValueAt(row, 2).toString());
            switch(tbAccount.getValueAt(row, 3).toString()){
                case "teacher" :
                    cbRole.setSelectedIndex(0);
                    break;
                default:
                    cbRole.setSelectedIndex(1);
                    break;
            }
            textsdt.setText(tbAccount.getValueAt(row, 4).toString());
            textHoVaTen.setText(tbAccount.getValueAt(row, 5).toString());
            switch(tbAccount.getValueAt(row, 6).toString()){
                case "CNTT" :
                    cbKhoa.setSelectedIndex(0);
                    break;
                default:
                    cbKhoa.setSelectedIndex(1);
                    break;
            }
        }
    }//GEN-LAST:event_tbAccountMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddNew;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btUpdate;
    private javax.swing.JComboBox<String> cbKhoa;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuexit;
    private javax.swing.JTable tbAccount;
    private javax.swing.JTextField textHoVaTen;
    private javax.swing.JTextField textsdt;
    private javax.swing.JTextField txtid;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
