/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControlCreateTest;
import information.TracNghiem;
import information.TuLuan;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import listrandom.CreateListInt;

/**
 *
 * @author binhminh
 */
public final class ViewCreateTest extends javax.swing.JFrame {

    /**
     * Creates new form CreateTest
     */
    private final int userID;
    private final ControlCreateTest createTest = new ControlCreateTest();
    private final ViewOperation question;
    
    
    DefaultTableModel modelCTN, modelCTL;
    DefaultTableModel tableCTN, tableCTL;
    private final ArrayList<TuLuan> LISTTB1;
    private final ArrayList<TracNghiem> LISTTB2;
    
    // overloading contructor
    public ViewCreateTest(ViewOperation s) {
        this.userID = s.getUserID();
        initComponents();
        this.question = s;
        //THU CONG======================================
        jTextField1.setVisible(false);
        jLabel3.setVisible(false);
        jTextField2.setVisible(false);
        jLabel4.setVisible(false);
        
        //SINH TU DONG=====================================
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        //==================================================
        
        LISTTB1 = createTest.ioTuLuan.readTapCauHoi();
        modelCTL = (DefaultTableModel) jTable1.getModel();
        hienThiTB1();

        LISTTB2 = createTest.iOTracNghiem.readTapCauHoi();
        modelCTN = (DefaultTableModel) jTable2.getModel();
        hienThiTB2();
        
        tableCTL = (DefaultTableModel) jTable3.getModel();
        tableCTN = (DefaultTableModel) jTable4.getModel();
    }
    
    public void hienThiTB2() {
        for (TracNghiem tn : LISTTB2) {
            modelCTN.addRow(new Object[]{
                tn.getChuong(), tn.getId(), tn.getUserID()
            });
        }
    }

    public void hienThiTB1() {
        for (TuLuan tl : LISTTB1) {
            modelCTL.addRow(new Object[]{
                tl.getChuong(), tl.getId(), tl.getUserID()
            });

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btQuayLai = new javax.swing.JButton();
        btSinhDe = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        btDaoCauHoi = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        btChon = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        doKho = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        btSinhDeTuDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tạo đề thi");
        setLocation(new java.awt.Point(400, 180));
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hệ thống tạo đề thủ công", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 36), java.awt.Color.red)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chương", "ID Tự luận", "user"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel6.setLayout(new java.awt.GridLayout(1, 3));

        jRadioButton3.setFont(jRadioButton3.getFont().deriveFont(jRadioButton3.getFont().getStyle() | java.awt.Font.BOLD, 17));
        jRadioButton3.setText("Tự Luận");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jRadioButton3);

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD, 15));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Số câu");
        jPanel6.add(jLabel3);
        jPanel6.add(jTextField1);

        jPanel7.setLayout(new java.awt.GridLayout(1, 3));

        jRadioButton4.setFont(jRadioButton4.getFont().deriveFont(jRadioButton4.getFont().getStyle() | java.awt.Font.BOLD, 17));
        jRadioButton4.setText("Trắc nghiệm");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jRadioButton4);

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() | java.awt.Font.BOLD, 15));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Số câu");
        jPanel7.add(jLabel4);
        jPanel7.add(jTextField2);

        btQuayLai.setFont(btQuayLai.getFont().deriveFont(btQuayLai.getFont().getStyle() | java.awt.Font.BOLD, 15));
        btQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/arrow-back-icon.png"))); // NOI18N
        btQuayLai.setText("Quay lại");
        btQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuayLaiActionPerformed(evt);
            }
        });

        btSinhDe.setFont(btSinhDe.getFont().deriveFont(btSinhDe.getFont().getStyle() | java.awt.Font.BOLD, 15));
        btSinhDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/korganizer-icon.png"))); // NOI18N
        btSinhDe.setText("Sinh đề");
        btSinhDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSinhDeActionPerformed(evt);
            }
        });

        btThoat.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Close-icon.png"))); // NOI18N
        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        btDaoCauHoi.setFont(btDaoCauHoi.getFont().deriveFont(btDaoCauHoi.getFont().getStyle() | java.awt.Font.BOLD));
        btDaoCauHoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/StandMixer-icon.png"))); // NOI18N
        btDaoCauHoi.setText("Đảo câu hỏi");
        btDaoCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDaoCauHoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSinhDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btDaoCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btQuayLai, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSinhDe, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btDaoCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextArea1.setBackground(java.awt.Color.white);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 178, 255));
        jTextArea1.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea1);

        btChon.setText("Chọn ");
        btChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonActionPerformed(evt);
            }
        });

        btXoa.setText("Xóa ");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChon, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(btChon, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chương ", "ID Tự Luận", "user"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chương ", "ID Trắc Nghiệm", "user"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setUpdateSelectionOnSort(false);
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable4);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chương", "ID Trắc Nghiệm", "user"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        doKho.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        doKho.setForeground(new java.awt.Color(0, 202, 255));
        doKho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        labelUserName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        labelUserName.setForeground(new java.awt.Color(0, 167, 255));
        labelUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(doKho, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(labelUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(91, 91, 91))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doKho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sinh đề thủ công", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hệ thống tạo đề ngẫu nhiên", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 1, 36), java.awt.Color.red)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.blue);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIME");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15", "45", "90" }));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.blue);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TYPE");

        jPanel9.setLayout(new java.awt.GridLayout(2, 1));

        jRadioButton2.setFont(jRadioButton2.getFont().deriveFont(jRadioButton2.getFont().getStyle() | java.awt.Font.BOLD, 20));
        jRadioButton2.setText("Câu tự luân");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(jRadioButton1.getFont().deriveFont(jRadioButton1.getFont().getStyle() | java.awt.Font.BOLD, 20));
        jRadioButton1.setText("Câu trắc nghiệm");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jPanel10.setLayout(new java.awt.GridLayout(4, 3));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("+");
        jPanel10.add(jLabel5);

        jLabel6.setText("Câu Trắc Nghiệm");
        jPanel10.add(jLabel6);

        jLabel7.setText("Câu Tự Luận");
        jPanel10.add(jLabel7);

        jLabel8.setText("Dễ");
        jPanel10.add(jLabel8);
        jPanel10.add(jTextField3);
        jPanel10.add(jTextField4);

        jLabel9.setText("Trung Bình");
        jPanel10.add(jLabel9);
        jPanel10.add(jTextField5);
        jPanel10.add(jTextField6);

        jLabel10.setText("Khó");
        jPanel10.add(jLabel10);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField7);
        jPanel10.add(jTextField8);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(347, 347, 347)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
        );

        btSinhDeTuDong.setBackground(java.awt.Color.lightGray);
        btSinhDeTuDong.setFont(btSinhDeTuDong.getFont().deriveFont(btSinhDeTuDong.getFont().getStyle() | java.awt.Font.BOLD, 36));
        btSinhDeTuDong.setForeground(java.awt.Color.red);
        btSinhDeTuDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Test-paper-icon.png"))); // NOI18N
        btSinhDeTuDong.setText("Sinh đề"); // NOI18N
        btSinhDeTuDong.setBorderPainted(false);
        btSinhDeTuDong.setSelected(true);
        btSinhDeTuDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSinhDeTuDongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSinhDeTuDong, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(59, 59, 59)
                .addComponent(btSinhDeTuDong, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        jTabbedPane1.addTab("Sinh đề tự động", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // hien thi nhap so cau tu luan SINH TU DONG
        
        if(jRadioButton2.isSelected()){
            jTextField4.setVisible(true);
            jTextField6.setVisible(true);
            jTextField8.setVisible(true);
        }else{
            jTextField4.setVisible(false);
            jTextField6.setVisible(false);
            jTextField8.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuayLaiActionPerformed
        this.setVisible(false);
        question.setVisible(true);
    }//GEN-LAST:event_btQuayLaiActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // hien thi de nhap so cau neu Cau Tu Luan duoc chon
        if(jRadioButton3.isSelected()){
            jLabel3.setVisible(true);
            jTextField1.setVisible(true);
        }else{
            jLabel3.setVisible(false);
            jTextField1.setVisible(false);
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void btSinhDeTuDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSinhDeTuDongActionPerformed
        // SINH DE TU DONG
        listrandom.CreateListInt RanD = new CreateListInt();
        //Phan Tu Luan==================================================
        // Tu luan

        ArrayList<TuLuan> listTest = new ArrayList<>();
        if (!jTextField4.getText().equals("")) { // De
            ArrayList<TuLuan> listCauDe = new ArrayList<>();
            for (TuLuan tl : LISTTB1) {
                if (tl.getDoKho().equals("easy")) {
                    listCauDe.add(tl);
                }
            }
            ArrayList<Integer> listSo;
            int n = Integer.parseInt(jTextField4.getText());
            if (n <= listCauDe.size()) {
                listSo = RanD.ListInt(n, listCauDe.size());
                for (int i = 0; i < listSo.size(); i++) {
                    listTest.add(listCauDe.get(listSo.get(i)));
                }
            }

        }

        if (!jTextField6.getText().equals("")) { // Trung binh
            ArrayList<TuLuan> listCauTrungBinh = new ArrayList<>();
            for (TuLuan tl : LISTTB1) {
                if (tl.getDoKho().equals("medium")) {
                    listCauTrungBinh.add(tl);
                }
            }
            ArrayList<Integer> listInt;
            int n = Integer.parseInt(jTextField6.getText());
            if (n <= listCauTrungBinh.size()) {
                listInt = RanD.ListInt(n, listCauTrungBinh.size());
                for (int i = 0; i < listInt.size(); i++) {
                    listTest.add(listCauTrungBinh.get(listInt.get(i)));
                }
            }

        }

        if (!jTextField8.getText().equals("")) { // Kho
            ArrayList<TuLuan> listCauKho = new ArrayList<>();
            for (TuLuan tl : LISTTB1) {
                if (tl.getDoKho().equals("hard")) {
                    listCauKho.add(tl);
                }
            }
            ArrayList<Integer> listInt;
            int n = Integer.parseInt(jTextField8.getText());
            if (n <= listCauKho.size()) {
                listInt = RanD.ListInt(n, listCauKho.size());
                for (int i = 0; i < listInt.size(); i++) {
                    listTest.add(listCauKho.get(listInt.get(i)));
                }
            }

        }

        for (TuLuan tl : listTest) {
            tableCTL.addRow(new Object[]{
                tl.getChuong(), tl.getId(), tl.getUserID()
            });
        }
        
        //==============================================================
        //Phan Trac Nghiem==============================================
        // Trac nghiem
        ArrayList<TracNghiem> listTest2 = new ArrayList<>();
        if (!jTextField3.getText().equals("")) { // De
            ArrayList<TracNghiem> listCauDe = new ArrayList<>();
            for (TracNghiem tn : LISTTB2) {
                if (tn.getDoKho().equals("easy")) {
                    listCauDe.add(tn);
                }
            }
            ArrayList<Integer> listSo;
            int n = Integer.parseInt(jTextField3.getText());
            if (n <= listCauDe.size()) {
                listSo = RanD.ListInt(n, listCauDe.size());
                for (int i = 0; i < listSo.size(); i++) {
                    listTest2.add(listCauDe.get(listSo.get(i)));
                }
            }

        }

        if (!jTextField5.getText().equals("")) { // Trung binh
            ArrayList<TracNghiem> listCauTrungBinh = new ArrayList<>();
            for (TracNghiem tn : LISTTB2) {
                if (tn.getDoKho().equals("medium")) {
                    listCauTrungBinh.add(tn);
                }
            }
            ArrayList<Integer> listInt;
            int n = Integer.parseInt(jTextField5.getText());
            if (n <= listCauTrungBinh.size()) {
                listInt = RanD.ListInt(n, listCauTrungBinh.size());
                for (int i = 0; i < listInt.size(); i++) {
                    listTest2.add(listCauTrungBinh.get(listInt.get(i)));
                }
            }

        }

        if (!jTextField7.getText().equals("")) { // Kho
            ArrayList<TracNghiem> listCauKho = new ArrayList<>();
            for (TracNghiem tn : LISTTB2) {
                if (tn.getDoKho().equals("hard")) {
                    listCauKho.add(tn);
                }
            }
            ArrayList<Integer> listInt;
            int n = Integer.parseInt(jTextField7.getText());
            if (n <= listCauKho.size()) {
                listInt = RanD.ListInt(n, listCauKho.size());
                for (int i = 0; i < listInt.size(); i++) {
                    listTest2.add(listCauKho.get(listInt.get(i)));
                }
            }

        }

        for (TracNghiem tn : listTest2) {
            tableCTN.addRow(new Object[]{
                tn.getChuong(), tn.getId(), tn.getUserID()
            });
        }
       
        
        if(jRadioButton2.isSelected() && jRadioButton1.isSelected()){
            createTest.sinhDeTuLuanVaTracNghiem(jTable3, jTable4);
        }else if(jRadioButton2.isSelected()){
            createTest.createTestTuLuan(jTable3);
        }else if(jRadioButton1.isSelected()){
            createTest.createTestTracNghiem(jTable4);  
        }else{
            JOptionPane.showMessageDialog(rootPane, "Bạn phải chọn loại đề muốn tạo ở TYPE", "NOTE", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btSinhDeTuDongActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // hien thi de nhap so cau neu Cau Trac Nghiem duoc chon
        if(jRadioButton4.isSelected()){
            jLabel4.setVisible(true);
            jTextField2.setVisible(true);
        }else{
            jLabel4.setVisible(false);
            jTextField2.setVisible(false);
            jTextField2.setText("");
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        if(JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn thoát?" , "NOTE", JOptionPane.YES_NO_OPTION) == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btThoatActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // hien thi noi dung cau tu luan
        jTable1.setRowSelectionAllowed(true);
        jTable2.setRowSelectionAllowed(false);
        if( evt.getClickCount() == 2){
            int r = jTable1.getSelectedRow();
            int id = (int) jTable1.getValueAt(r, 1);
            int uid = (int) jTable1.getValueAt(r, 2);
            TuLuan ctl = new TuLuan();
            // hien thi cua bang trac nghiem (2)
            ctl = (TuLuan) createTest.hienThiCauHoi( id, uid , 2);
            if (ctl != null) {
                jTextArea1.setText(ctl.getDeBai());
                doKho.setText(ctl.getDoKho());
                labelUserName.setText(createTest.showName(uid));
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // hien thi noi dung cau trac nghiem
        jTable1.setRowSelectionAllowed(false);
        jTable2.setRowSelectionAllowed(true);
        if(evt.getClickCount() == 2){
            TracNghiem ctn = new TracNghiem();
            int r = jTable2.getSelectedRow();
            int id = (int) jTable2.getValueAt(r, 1);
            int uid = (int) jTable2.getValueAt(r, 2);
            ctn = (TracNghiem) createTest.hienThiCauHoi(id, uid ,1);
            if (ctn != null) {
                jTextArea1.setText(ctn.getDeBai());
                doKho.setText(ctn.getDoKho());
                labelUserName.setText(createTest.showName(uid));
            }
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void btChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonActionPerformed
        // them cau hoi
        int i1=0,i2=0;
        if(!jTextField1.getText().equals("")){
            i1 =  Integer.valueOf(jTextField1.getText().trim());
        }
        if(!jTextField2.getText().equals("")){
            i2 = Integer.valueOf(jTextField2.getText().trim());
        }
        if (jTable1.getRowSelectionAllowed()) {
            if (jTable3.getRowCount() >= i1) {
                JOptionPane.showMessageDialog(rootPane, "Không thể thêm câu hỏi");
            } else {
                int count = jTable1.getSelectedRow();
                tableCTL.addRow(new Object[]{
                    jTable1.getValueAt(count, 0), jTable1.getValueAt(count, 1), jTable1.getValueAt(count, 2)
                });
            }

        } else if (jTable2.getRowSelectionAllowed()) {
            if (jTable4.getRowCount() >= i2) {
                JOptionPane.showMessageDialog(rootPane, "Không thể thêm câu hỏi");
            }else {
                int count = jTable2.getSelectedRow();
                tableCTN.addRow(new Object[]{
                    jTable2.getValueAt(count, 0), jTable2.getValueAt(count, 1), jTable2.getValueAt(count, 2)
                });
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Hãy chọn 1 hàng", "NOTE", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btChonActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // xoa 1 dong trong bảng
        if (jTable3.getRowSelectionAllowed()) {
            if (jTable3.getRowCount() <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Không thể xóa câu hỏi");
            } else {
                int count = jTable3.getSelectedRow();
                tableCTL.removeRow(count);
            }

        } else if (jTable4.getRowSelectionAllowed()) {
            if (jTable4.getRowCount() <= 0 ) {
                JOptionPane.showMessageDialog(rootPane, "Không thể xóa câu hỏi");
            }else {
                int count = jTable4.getSelectedRow();
                tableCTN.removeRow(count);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Hãy chọn 1 hàng", "NOTE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        jTable3.setRowSelectionAllowed(true);
        jTable4.setRowSelectionAllowed(false);
    }//GEN-LAST:event_jTable3MouseClicked
    // bang cau hoi da duoc chon
    
    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        jTable3.setRowSelectionAllowed(false);
        jTable4.setRowSelectionAllowed(true);
    }//GEN-LAST:event_jTable4MouseClicked

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void btSinhDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSinhDeActionPerformed
        // Sinh de thu cong
        if(jTable3.getRowCount()>0 && jTable4.getRowCount()>0){
            createTest.sinhDeTuLuanVaTracNghiem(jTable3, jTable4);
        }else if(jTable3.getRowCount() > 0){
            createTest.createTestTuLuan(jTable3);
        }else{
            createTest.createTestTracNghiem(jTable4);
        }
    }//GEN-LAST:event_btSinhDeActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // Hien thi nhap so cau trac nghiem bang SINH TU DONG
        if(jRadioButton1.isSelected()){
            jTextField3.setVisible(true);
            jTextField5.setVisible(true);
            jTextField7.setVisible(true);
        }else{
            jTextField3.setVisible(false);
            jTextField5.setVisible(false);
            jTextField7.setVisible(false);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btDaoCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDaoCauHoiActionPerformed
        
        // Tron Cau Hoi
        int n= jTable3.getRowCount();
        if(n > 1){
            ArrayList<TuLuan> list = new ArrayList();
            TuLuan tl ;
            for(int i = 0 ; i < n; i++){
                tl = new TuLuan();
                tl.setChuong((int) jTable3.getValueAt(i, 0));
                tl.setId((int) jTable3.getValueAt(i, 1));
                tl.setUserID((int) jTable3.getValueAt(i,2));
                list.add(tl);
            }
            ArrayList<Integer> numbers = new ArrayList();
            listrandom.CreateListInt rand = new CreateListInt();
            numbers = rand.ListInt(n, n);
            for(int i=0 ; i < n ;i++){
                tableCTL.removeRow(0);
                tl = list.get(numbers.get(i));
                tableCTL.addRow(new Object[]{
                   tl.getChuong(), tl.getId(), tl.getUserID()
                });
            }
        }
        int m = jTable4.getRowCount();
        if( m > 1){
            ArrayList<TracNghiem> list = new ArrayList();
            TracNghiem tn; 
            for(int i = 0 ; i < m; i++){
                tn = new TracNghiem();
                tn.setChuong((int) jTable4.getValueAt(i, 0));
                tn.setId((int) jTable4.getValueAt(i, 1));
                tn.setUserID((int) jTable4.getValueAt(i,2));
                list.add(tn);
            }
            ArrayList<Integer> numbers = new ArrayList();
            listrandom.CreateListInt rand = new CreateListInt();
            numbers = rand.ListInt(m, m);
            for(int i=0; i < m ;i++){
                tableCTN.removeRow(0);
                tn = list.get(numbers.get(i));
                tableCTN.addRow(new Object[]{
                   tn.getChuong(), tn.getId(), tn.getUserID()
                });
            }
        }
        
        JOptionPane.showMessageDialog(rootPane, "Đề đã được đảo thứ tự câu hỏi", "NOTE", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btDaoCauHoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChon;
    private javax.swing.JButton btDaoCauHoi;
    private javax.swing.JButton btQuayLai;
    private javax.swing.JButton btSinhDe;
    private javax.swing.JButton btSinhDeTuDong;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel doKho;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel labelUserName;
    // End of variables declaration//GEN-END:variables
}
