spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/database
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 9100

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka





